name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python=3.9  # Aggiungi Python se necessario
  - r-base=4.2  # Versione di R
  - r-devtools
  - r-irkernel
  - r-shiny
  - r-tidyverse
  - r-sf
  - r-readr
  - r-mapview
  - r-e1071
  - r-class
  - r-units
  - r-geojsonio
  - r-dplyr
  - r-ggplot2
  - r-tidygeocoder
  - gdal
  - proj
  - geos
  - udunits2
  - pandoc
  - jupyterlab
