name: mybinder-env
channels:
  - conda-forge
dependencies:
  - r-leaflet  
  - r-mapview   
  - python=3.9  
  - r-base=4.2  
  - r-devtools
  - r-irkernel
  - r-shiny
  - r-tidyverse
  - r-sf
  - r-osmdata
  - r-readr
  - r-e1071
  - r-class
  - r-units
  - r-geojsonio
  - r-dplyr
  - r-ggplot2
  - r-tidygeocoder
  - r-codetools
  - gdal
  - proj
  - geos
  - udunits2
  - pandoc
  - jupyterlab
